services:

  postgres:
    container_name: zcoin_postgres
    image: postgres:14.0
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=X#wxpACw@c!WwUwb
      - POSTGRES_DB=zcoin
    ports:
      - "5432:5432"
    volumes:
      - zcoin_db_data:/var/lib/postgresql/data

  redis:
    container_name: zcoin_redis
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - zcoin_redis_data:/data

volumes:
  zcoin_db_data:
    driver: local
  zcoin_redis_data:
    driver: local

networks:
  default:
    name: zcoin